config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kittens

  # Defines the root path route ("/")
  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
# frozen_string_literal: true

# Kitten controller for routes
class KittensController < ApplicationController
  before_action :set_kitten, only: %i[show edit update destroy]

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      respond_to do |format|
        format.html { redirect_to @kitten, notice: 'You added a kitten :3' }
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def edit; end

  def update
    if @kitten.update(kitten_params)
      respond_to do |format|
        format.html { redirect_to @kitten, notice: 'You edited the kitten :D' }
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @kitten.destroy

    redirect_to root_path, status: :see_other, notice: 'You deleted the kitten :c'
  end

  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten_form.html.erb
<%= form_with model: @kitten do |f| %>
    <div class="simple-field">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
    </div>
    <div class="numeric-fields">
        <div class="numeric-field">
            <%= f.label :age %>
            <%= f.number_field :age, min: 1 %>
        </div>
        <div class="numeric-field">
            <%= f.label :cuteness %>
            <%= f.number_field :cuteness, in: 1..5 %>
        </div>
        <div class="numeric-field">
            <%= f.label :softness %>
            <%= f.number_field :softness, in: 1..5 %>
        </div>
    </div>
    <div class="actions">
        <%= f.submit action_name, class: 'submit-button' %>
        <% if show_delete %>
            <%= link_to 'Delete Kitten', @kitten, data: { turbo_method: :delete } %>
        <% end %>
    </div>
<% end %>

app/views/kittens/edit.html.erb
<div class="form-container">
    <p class="form-title">Edit Kitten</p>
    <%= render partial: 'kitten_form', locals: { action_name: 'Update Kitten', show_delete: true } %>
</div>

app/views/kittens/index.html.erb
<% if flash[:notice] %>
    <div class="notice-negative"> <%= flash[:notice] %> </div>
<% end %>
<div class="kitten-container">
    <% if @kittens.empty? %>
        <p class="empty-message" > No kittens yet :( </p>
    <% else %>
        <% @kittens.each do |kitten| %>
            <div class="kitten-card">
                <%= link_to kitten.name, kitten_path(kitten), class: 'card-title' %>
                <div class="card-field">
                    <p class="card-label">Age</p>
                    <p class="card-text"> <%= kitten.age %> </p>
                </div>
                <div class="card-field">
                    <p class="card-label">Cuteness</p>
                    <p class="card-text"> <%= kitten.cuteness %> </p>
                </div>
                <div class="card-field">
                    <p class="card-label">Softness</p>
                    <p class="card-text"> <%= kitten.softness %> </p>
                </div>
                <div class="card-actions">
                    <%= link_to 'Edit Kitten', edit_kitten_path(kitten), method: :patch %>
                    <%= link_to 'Delete Kitten', kitten, data: { turbo_method: :delete } %>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/kittens/new.html.erb
<div class="form-container">
    <p class="form-title">New Kitten</p>
    <%= render partial: 'kitten_form', locals: { action_name: 'Add Kitten', show_delete: false } %>
</div>

app/views/kittens/show.html.erb
<div class="kitten-details">
    <% if flash[:notice] %>
        <div class="notice-positive"> <%= flash[:notice] %> </div>
    <% end %>
    <p class="kitten-name"> <%= @kitten.name %> </p>
    <div class="kitten-data-container">
        <div class="kitten-data kitten-age">
            <div class="kitten-field">Age</div>
            <div class="kitten-value"> <%= @kitten.age %> </div>
        </div>
        <div class="kitten-data kitten-cute">
            <div class="kitten-field">Cuteness</div>
            <div class="kitten-value"> <%= @kitten.cuteness %> </div>
        </div>
        <div class="kitten-data kitten-soft">
            <div class="kitten-field">Softness</div>
            <div class="kitten-value"> <%= @kitten.softness %> </div>
        </div>
    </div>
    <div class="actions">
        <%= link_to 'Edit Kitten', edit_kitten_path(@kitten), method: :patch %>
        <%= link_to 'Delete Kitten', @kitten, data: { turbo_method: :delete } %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kittens API</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar">
      <div class="navbar-home">
        <%= link_to 'Kittens', root_path, class: 'navbar-title' %>
      </div>
      <div class="navbar-options">
        <%= link_to 'Add Kitten', new_kitten_path, class: 'navbar-option' %>
      </div>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>